/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ybot.glb --transform --types 
Files: public/ybot.glb [11.36MB] > C:\Users\USER\Desktop\test\my-3d-test\ybot-transformed.glb [198.6KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils, type GLTF } from 'three-stdlib'
import poseDataRaw from '../pose_output.json'

const poseData = poseDataRaw as any[];

type ActionName = 'mixamo.com'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Alpha_Surface: THREE.SkinnedMesh
    Alpha_Joints: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
    mixamorigSpine: THREE.Bone
    mixamorigSpine1: THREE.Bone
    mixamorigSpine2: THREE.Bone
    mixamorigNeck: THREE.Bone
    mixamorigLeftShoulder: THREE.Bone
    mixamorigLeftArm: THREE.Bone
    mixamorigLeftHandThumb1: THREE.Bone
    mixamorigLeftHandThumb2: THREE.Bone
    mixamorigLeftHandIndex1: THREE.Bone
    mixamorigLeftHandIndex2: THREE.Bone
    mixamorigLeftHandRing1: THREE.Bone
    mixamorigLeftHandRing2: THREE.Bone
    mixamorigLeftHandPinky1: THREE.Bone
    mixamorigLeftHandPinky2: THREE.Bone
    mixamorigLeftHandPinky3: THREE.Bone
    mixamorigRightShoulder: THREE.Bone
    mixamorigRightArm: THREE.Bone
    mixamorigRightHandThumb1: THREE.Bone
    mixamorigRightHandThumb2: THREE.Bone
    mixamorigRightHandIndex1: THREE.Bone
    mixamorigRightHandIndex2: THREE.Bone
    mixamorigRightHandRing1: THREE.Bone
    mixamorigRightHandRing2: THREE.Bone
    mixamorigRightHandPinky1: THREE.Bone
    mixamorigRightHandPinky2: THREE.Bone
    mixamorigRightHandPinky3: THREE.Bone
    mixamorigLeftUpLeg: THREE.Bone
    mixamorigLeftLeg: THREE.Bone
    mixamorigLeftFoot: THREE.Bone
    mixamorigLeftToeBase: THREE.Bone
    mixamorigRightUpLeg: THREE.Bone
    mixamorigRightLeg: THREE.Bone
    mixamorigRightFoot: THREE.Bone
    mixamorigRightToeBase: THREE.Bone
  }
  materials: {
    Alpha_Body_MAT: THREE.MeshStandardMaterial
    Alpha_Joints_MAT: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Ybot(props: React.ComponentProps<'group'>) {
  const group = React.useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/ybot-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = (useGraph(clone) as unknown) as GLTFResult
  const { actions } = useAnimations(animations, group)

  // --- 초기 포즈 쿼터니언(스냅샷)을 저장할 Ref ---
  const initialQuats = React.useRef<{ [key: string]: THREE.Quaternion }>({});

  // 1. 이미지처럼 깨끗한 마네킹 재질 설정
  const mannequinMaterial = React.useMemo(() => (
    <meshStandardMaterial 
      color="#ffffff" 
      roughness={0.2} 
      metalness={0.1} 
    />
  ), [])

  // 2. 애니메이션 재생 및 관절 포인트 동적 추가 (기존 뼈대 분리 방지)
  React.useEffect(() => {
    // 2-1. T-Pose 초기 회전 상태(Rest Pose) 캡처
    Object.values(nodes).forEach((node) => {
      if ((node as THREE.Bone).isBone) {
        initialQuats.current[node.name] = node.quaternion.clone();
      }
    });

    // 2-2. 뼈대에 직접 관절 구체 추가 (Three.js 씬 그래프에 안전하게 붙임)
    const joints = ['LeftArm', 'RightArm', 'LeftLeg', 'RightLeg'] as const;
    const sphereGeo = new THREE.SphereGeometry(0.04);
    const sphereMat = new THREE.MeshStandardMaterial({
      color: 'purple',
      emissive: 'purple',
      emissiveIntensity: 0.5,
    });

    const addedMeshes: THREE.Mesh[] = [];

    joints.forEach((joint) => {
      const boneName = `mixamorig${joint}` as keyof GLTFResult['nodes'];
      const bone = nodes[boneName] as THREE.Bone;
      if (bone && bone.isBone) {
        const mesh = new THREE.Mesh(sphereGeo, sphereMat);
        bone.add(mesh);
        addedMeshes.push(mesh);
      }
    });

    // 컴포넌트 언마운트 시 정리
    return () => {
      addedMeshes.forEach(mesh => {
        if (mesh.parent) mesh.parent.remove(mesh);
      });
      sphereGeo.dispose();
      sphereMat.dispose();
    };
  }, [actions, nodes]);

  // 3. MediaPipe JSON 데이터를 읽어와서 매 프레임 관절에 적용시키는 부분
  useFrame((state) => {
    if (!poseData || poseData.length === 0) return;
    
    // JSON 데이터의 마지막 프레임 시간 (반복 재생용)
    const maxTime = poseData[poseData.length - 1].timestamp_ms;
    // 현재 경과 시간을 ms 단위로 변환 후 루프
    const elapsed = (state.clock.getElapsedTime() * 1000) % maxTime;
    
    // 현재 시간에 가장 가까운 포즈 프레임 검색
    const currentFrame = poseData.find((d: any) => d.detected && d.timestamp_ms >= elapsed) 
                      || poseData[poseData.length - 1];

    if (currentFrame && currentFrame.landmarks && currentFrame.landmarks.length > 0) {
      const lms = currentFrame.landmarks;

      // 3-1. 매 프레임마다 모든 뼈대를 초기 T-Pose 상태로 초기화하여 꼬임 누적(Jitter/Twist) 방지
      Object.keys(initialQuats.current).forEach((boneName) => {
        const bone = nodes[boneName as keyof GLTFResult['nodes']] as THREE.Bone;
        if (bone) bone.quaternion.copy(initialQuats.current[boneName]);
      });
      // 뼈대들의 월드 매트릭스를 강제 업데이트하여 T-Pose 공간 정보 확보
      nodes.mixamorigHips.updateWorldMatrix(true, true);

      // 3-2. 로컬 방향 타겟팅 함수 (World-to-Local 역변환) 
      const trackBone = (
        parentBone: THREE.Bone | undefined,
        childBone: THREE.Bone | undefined,
        startId: number,
        endId: number
      ) => {
        if (!parentBone || !childBone) return;

        const p1 = lms.find((p: any) => p.id === startId);
        const p2 = lms.find((p: any) => p.id === endId);
        if (!p1 || !p2) return;

        // MediaPipe는 화면 왼쪽부터 오른쪽이 +X, 위에서 아래가 +Y, 가까울수록 -Z 입니다.
        // Three.js 좌표와 맞추기 위해 x, y 배율을 보정합니다.
        const mpStart = new THREE.Vector3(-p1.x, -p1.y, -p1.z);
        const mpEnd   = new THREE.Vector3(-p2.x, -p2.y, -p2.z);

        // 월드 공간 상에서 자식(팔꿈치 등)이 가야할 이상적인 방향
        const targetWorldDir = new THREE.Vector3().subVectors(mpEnd, mpStart).normalize();

        // 현재(기본 T-Pose) 부모 뼈의 중심 좌표와 자식 뼈의 중심 좌표
        const currentParentPos = new THREE.Vector3();
        parentBone.getWorldPosition(currentParentPos);
        const currentChildPos = new THREE.Vector3();
        childBone.getWorldPosition(currentChildPos);

        // 현재 로컬 공간상에서 자식이 위치해 있는 방향 벡터 (내 팔의 기본 방향)
        const currentLocalDir = new THREE.Vector3().subVectors(currentChildPos, currentParentPos).normalize();
        parentBone.worldToLocal(currentLocalDir); // 월드 벡터를 내 뼈대의 로컬 뷰로 역변환

        // 로컬 공간상에서 자식이 향했으면 하는 타겟 방향 벡터 (가야할 곳)
        const targetLocalDir = targetWorldDir.clone();
        // 회전만 적용해야 하므로 transformDirection 사용
        const mInverse = new THREE.Matrix4().copy(parentBone.matrixWorld).invert();
        targetLocalDir.transformDirection(mInverse).normalize();

        // 뼈가 향해있는 현재 로컬 방향을, MediaPipe가 지시하는 타겟 로컬 방향으로 회전시킬 각도(Quaternion)
        const deltaQuat = new THREE.Quaternion().setFromUnitVectors(currentLocalDir, targetLocalDir);

        // 초기 T-Pose 회전값 위에 각도를 곱해서 적용하고 행렬 업데이트
        parentBone.quaternion.multiply(deltaQuat);
        parentBone.updateWorldMatrix(true, true);
      };

      // 팔 매핑 (Base -> Target)
      trackBone(nodes.mixamorigLeftArm, (nodes as any).mixamorigLeftForeArm as THREE.Bone, 11, 13);
      trackBone((nodes as any).mixamorigLeftForeArm as THREE.Bone, (nodes as any).mixamorigLeftHand as THREE.Bone, 13, 15);
      trackBone(nodes.mixamorigRightArm, (nodes as any).mixamorigRightForeArm as THREE.Bone, 12, 14);
      trackBone((nodes as any).mixamorigRightForeArm as THREE.Bone, (nodes as any).mixamorigRightHand as THREE.Bone, 14, 16);

      // 다리 매핑
      // 무릎 방향은 엉덩이(23, 24)와 발목(27, 28) 사이 무릎(25, 26)을 타겟으로 함
      trackBone(nodes.mixamorigLeftUpLeg, nodes.mixamorigLeftLeg, 23, 25);
      trackBone(nodes.mixamorigLeftLeg, nodes.mixamorigLeftFoot, 25, 27);
      trackBone(nodes.mixamorigRightUpLeg, nodes.mixamorigRightLeg, 24, 26);
      trackBone(nodes.mixamorigRightLeg, nodes.mixamorigRightFoot, 26, 28);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="mixamorigHips_$AssimpFbx$_PreRotation" position={[0, 99.792, 0]}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        {/* 모델 본체에 마네킹 재질 적용 */}
        <skinnedMesh name="Alpha_Surface" geometry={nodes.Alpha_Surface.geometry} skeleton={nodes.Alpha_Surface.skeleton}>
          {mannequinMaterial}
        </skinnedMesh>
        <skinnedMesh name="Alpha_Joints" geometry={nodes.Alpha_Joints.geometry} skeleton={nodes.Alpha_Joints.skeleton}>
          {mannequinMaterial}
        </skinnedMesh>
      </group>
    </group>
  )
}

useGLTF.preload('/ybot-transformed.glb')
